[build-system]
requires = ['setuptools>=42']
build-backend = 'setuptools.build_meta'

[tool.isort]
line_length = 79
float_to_top=true
include_trailing_comma = true
multi_line_output = 3

[tool.black]
line_length = 79