#https://github.com/caleb531/automata/blob/main/.github/workflows/build.yml

# This workflow will build the Python project and build a wheel of the current release (*without* publishing to PyPI).

name: build

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Python 3
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v2.0.0

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Install pypa/build
      run: python -m pip install build --user

    - name: Build a binary wheel and a source tarball
      run: python -m build --sdist --wheel --outdir dist/ .